### ISSUE TITLE
[Bug] Velocity version is not detected, only Bungeecord

### ISSUE THREAD

**Issue by 3F-1** [Bram1903/MinecraftPlayerCrasher#15]
```
[04:57:52 ERROR]: Unable to load plugin plugins/PlayerCrasher-2.5.0.jar
com.velocitypowered.api.plugin.InvalidPluginException: The plugin file PlayerCrasher-2.5.0.jar appears to be a Bukkit or BungeeCord plugin. Velocity does not support Bukkit or BungeeCord plugins.
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.getSerializedPluginInfo(JavaPluginLoader.java:161) ~[velocity.jar:3.3.0-SNAPSHOT (git-aa4e8780-b401)]
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.loadCandidate(JavaPluginLoader.java:62) ~[velocity.jar:3.3.0-SNAPSHOT (git-aa4e8780-b401)]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:96) ~[velocity.jar:3.3.0-SNAPSHOT (git-aa4e8780-b401)]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:362) ~[velocity.jar:3.3.0-SNAPSHOT (git-aa4e8780-b401)]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:239) ~[velocity.jar:3.3.0-SNAPSHOT (git-aa4e8780-b401)]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:71) ~[velocity.jar:3.3.0-SNAPSHOT (git-aa4e8780-b401)]
```

**Comment by Bram1903** [comment]
Hey @3F-1,

I am making everything ready for the proxy support release, and that's why the README already states I support Velocity and Bungeecord (not really a smart idea), but at the moment the latest release only works on Bukkit. I will most probably make a release later today, but you can already download the latest build from the GitHub build workflow here: https://github.com/Bram1903/MinecraftPlayerCrasher/actions/runs/9826715098/artifacts/1674903532

Kind regards,
Bram
